<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <!-- <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8"> -->
      <span class="brand-text font-weight-light">&nbsp;&nbsp;Stuff Good !</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block"><?php echo $myData['full_name']; ?></a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="./index.php" class="nav-link <?php if(preg_match("#index.php#", $_SERVER['SCRIPT_NAME']) > 0) echo "active"; ?>">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
                <!-- <span class="right badge badge-danger"></span> -->
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="./pemesanan.php" class="nav-link <?php if(preg_match("#/pemesanan.php#", $_SERVER['SCRIPT_NAME']) > 0) echo "active"; ?>">
              <i class="nav-icon fas fa-shopping-cart"></i>
              <p>
                Pemesanan
                <!-- <span class="right badge badge-danger"></span> -->
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="./daftar_pemesanan.php" class="nav-link <?php if(preg_match("#daftar_pemesanan.php#", $_SERVER['SCRIPT_NAME']) > 0) echo "active"; ?>">
              <i class="nav-icon fas fa-list"></i>
              <p>
                Daftar Pemesanan
                <!-- <span class="right badge badge-danger"></span> -->
              </p>
            </a>
          </li>
          <li class="nav-header">Data Manage</li>
          
          <li class="nav-item">
            <a href="./drone.php" class="nav-link <?php if(preg_match("#drone.php#", $_SERVER['SCRIPT_NAME']) > 0) echo "active"; ?>">
              <i class="nav-icon fas fa-paper-plane"></i>
              <p>
                Data Sepatu
                <!-- <span class="right badge badge-danger"></span> -->
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="./data_pemesan.php" class="nav-link <?php if(preg_match("#data_pemesan.php#", $_SERVER['SCRIPT_NAME']) > 0) echo "active"; ?>">
              <i class="nav-icon fas fa-users"></i>
              <p>
                Data Pemesan
                <!-- <span class="right badge badge-danger"></span> -->
              </p>
            </a>
          </li>
          <!-- <li class="nav-header">LABELS</li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-circle text-danger"></i>
              <p class="text">Nama : Galang</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-circle text-warning"></i>
              <p>Warning</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-circle text-info"></i>
              <p>Informational</p>
            </a>
          </li> -->
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>